from adwe.services.errors import TestExecutionError
from adwe.services.execution_policy import Operation, require_operation
from adwe.services.git_branch import create_branch
from adwe.services.git_commit import commit_changes
from adwe.services.git_push import push_branch
from adwe.services.github_pr import create_pull_request
from adwe.services.patch_apply import apply_patch
from adwe.services.test_runner import run_tests
from adwe.services.workspace import repository_workspace


def apply_patch_workflow(
    repository_url: str,
    branch_name: str,
    diff: str,
    commit_message: str,
    test_command: list[str] | None = None,
    dry_run: bool = False,
    push: bool = False,
    open_pr: bool = False,
    pr_title: str | None = None,
    pr_body: str | None = None,
) -> dict:
    require_operation(Operation.PATCH_EXECUTION)
    with repository_workspace(repository_url) as repo_path:
        create_branch(repo_path, branch_name)
        apply_patch(repo_path, diff)

        test_result = None
        if test_command:
            test_result = run_tests(repo_path, test_command)

            if not test_result["passed"]:
                raise TestExecutionError(
                    "Tests failed with exit code "
                    f"{test_result['exit_code']}\n\n"
                    f"STDOUT:\n{test_result.get('stdout', '')[-4000:]}\n\n"
                    f"STDERR:\n{test_result.get('stderr', '')[-4000:]}"
    )

        if dry_run:
            return {
                "branch_name": branch_name,
                "commit_sha": None,
                "status": "validated",
                "test_result": test_result,
                "pull_request": None,
            }

        commit_sha = commit_changes(repo_path, commit_message)

        pushed = False
        if push or open_pr:
            push_branch(repo_path, branch_name)
            pushed = True

        pull_request = None
        if open_pr:
            pull_request = create_pull_request(
                repository_url=repository_url,
                branch_name=branch_name,
                title=pr_title or commit_message,
                body=pr_body or "Generated by ADWE.",
            )

        return {
            "branch_name": branch_name,
            "commit_sha": commit_sha,
            "status": "committed",
            "test_result": test_result,
            "pushed": pushed,
            "pull_request": pull_request,
        }
